"""Generates `vendorizado/forja.py` — the whole survey, no clone, downloadable via `curl -O`.

nature: fix — this generator only concatenates real code from the `forja`
package (it never rewrites anything by hand) and fails loud if the result does
not compile. A vendored file that "almost" works is worse than none: someone
trusted it without installing anything else.

Why this exists: `git clone` is the smallest friction this project already
asks for, and it is still bigger than the friction of competitors that run via
`npx` with no clone at all (measured on 08/20 — 13 stars, less friction). This
does not reduce the friction of the WHOLE FORGE — it reduces the friction of
the FIRST reading, the survey, which is the README's 30-second demo. Compiling
spec → artifact still requires the real package (it uses
`censo/ecossistema.json`, which makes no sense to ship standalone).

    python vendorizar.py            # writes vendorizado/forja.py
    python vendorizar.py --conferir # does not write; exits 1 if the file diverges

Once published (public repository — a separate gate):

    curl -O https://raw.githubusercontent.com/marquesPablo/loadline/main/vendorizado/forja.py
    python forja.py /path/to/your/project

Zero dependencies, because `forja/spec.py` and `forja/vistoria.py` are already
zero dependencies — the vendored file inherits the same property, and check BZ
proves it by running the GENERATED file, never just compiling it.

The technique is the same as `operacoes/juntar.py`: `from __future__ import
annotations` can only be the FIRST statement in the file, and concatenating two
modules with `cat` (or `+`) puts the second one in the middle — this generator
hoists a single copy, at the top, and drops the rest.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

RAIZ = Path(__file__).resolve().parent
FONTES = (RAIZ / "forja" / "spec.py", RAIZ / "forja" / "vistoria.py")
SAIDA = RAIZ / "vendorizado" / "forja.py"

_FUTURE = re.compile(r"^from __future__ import .*\n", re.M)
_IMPORT_RELATIVO = re.compile(r"^from \.spec import .*\n", re.M)

_CLI = '''

# --------------------------------------------------------------- CLI -------
#
# The part that did NOT come from the package: a thin wrapper, only so this
# file can run on its own. It is the same logic as
# `forja/__main__.py::_vistoria`, with no `--adotar`/`--html`/`--baseline` —
# this file is only the READING, the README's 30-second demo. For the rest,
# a real `pip install` or `git clone`.

import sys as _sys
from datetime import date as _date


def _console_em_utf8() -> None:
    for stream in (_sys.stdout, _sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[union-attr]
        except (AttributeError, ValueError, OSError):
            pass


def main(argv: list[str] | None = None) -> int:
    _console_em_utf8()
    argv = list(_sys.argv[1:] if argv is None else argv)
    raiz = Path(argv[0]) if argv else Path(".")
    hoje = _date.today().isoformat()

    pasta = achar_pasta(raiz)
    if pasta is None:
        print(f"survey · {raiz} · on {hoje}")
        print("=" * LARGURA)
        print("No agents folder found here. Looked, in this order:")
        for relativo in PASTAS:
            print(f"     {raiz / relativo}")
        print()
        print("REFUSED — read nothing, and will not return green for that.    (exit 2)")
        return 2

    roster = ler_roster(pasta)
    if not roster:
        print(f"survey · {pasta} · on {hoje}")
        print("=" * LARGURA)
        print("The folder exists and there is no agent inside it.")
        print()
        print("REFUSED — zero agents read is not zero defects.                 (exit 2)")
        return 2

    achados = vistoriar(roster)
    for linha in relatorio(roster, achados, pasta, hoje):
        print(linha)

    print()
    if not achados:
        print("PASS — every agent read declares the six things.                (exit 0)")
        return 0
    print("FAIL                                                           (exit 1)")
    print()
    print("  This is the vendored `forja.py` — the survey only. `--adotar`, `--html`,")
    print("  `--baseline` and spec → artifact compilation need the whole package:")
    print("  `git clone https://github.com/marquesPablo/loadline && cd loadline`.")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
'''


def gerar() -> str:
    partes = [
        '"""forja.py — vendored, survey only: reads the agents you already have.\n\n'
        "Generated by `vendorizar.py` from the real `forja` package — editing this\n"
        "file by hand edits a copy; the original lives in `forja/spec.py` and\n"
        "`forja/vistoria.py`. Zero dependencies: only the Python 3.10+ standard library.\n\n"
        "    python forja.py /path/to/your/project\n\n"
        'The whole package (spec compilation, `--adotar`, `--html`, `--baseline`,\n'
        "comparison mode) is at https://github.com/marquesPablo/loadline\n"
        '"""\n',
        "from __future__ import annotations\n",
    ]
    for fonte in FONTES:
        texto = fonte.read_text(encoding="utf-8")
        texto = _FUTURE.sub("", texto, count=1)
        texto = _IMPORT_RELATIVO.sub("", texto, count=1)
        partes.append(f"\n# {'=' * 68}\n# {fonte.relative_to(RAIZ)}\n# {'=' * 68}\n")
        partes.append(texto.strip("\n"))
        partes.append("\n")
    partes.append(_CLI.strip("\n") + "\n")
    return "\n".join(partes)


def _console_em_utf8() -> None:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[union-attr]
        except (AttributeError, ValueError, OSError):
            pass


def main(argv: list[str] | None = None) -> int:
    _console_em_utf8()
    argv = list(sys.argv[1:] if argv is None else argv)
    conferir = "--conferir" in argv

    gerado = gerar()

    # Fails loud, never silent: a vendored file that does not compile is the
    # worst of both worlds — it looks installable and does not run. `compile()`,
    # not `ast.parse` — the parser accepts `from __future__` outside the top;
    # the compiler is what fails it (the same lesson as check BJ/`operacoes/juntar.py`).
    compile(gerado, str(SAIDA), "exec")

    if conferir:
        atual = SAIDA.read_text(encoding="utf-8") if SAIDA.is_file() else None
        if atual == gerado:
            print(f"in sync  {SAIDA} matches the real `forja` package")
            return 0
        print(f"STALE  {SAIDA} diverges from the `forja` package — run `python vendorizar.py`")
        return 1

    SAIDA.parent.mkdir(parents=True, exist_ok=True)
    SAIDA.write_text(gerado, encoding="utf-8")
    print(f"✓ {SAIDA}  ·  {len(gerado.encode('utf-8'))} bytes, zero dependencies")
    print()
    print("  Check with:  python vendorizado/forja.py exemplos/roster-de-exemplo")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
