"""Joins the probes of two or more operations into a single `sondas.py`.

nature: fix — when it cannot join, it says what collided and writes nothing.
A half-written file is worse than no file.

    python operacoes/juntar.py instrucao-que-nao-mente readme-que-nao-mente \\
        --saida /path/to/your/repo/sondas.py

Why this exists, and is not a `cat`: every operation `sondas.py` opens with
`from __future__ import annotations`, and Python requires that line to be the
FIRST statement in the file. Concatenating two files with `cat` puts the second
one in the middle, and the result dies with `SyntaxError` on import — after it
has already overwritten the `sondas.py` of whoever tried.

What it does, in three rules:

  1. `from __future__` comes out of all of them and comes back once, at the top.
  2. The other `import`s are gathered, deduplicated and sorted.
  3. A METRIC PATTERN collision between two operations is a REFUSAL. Two probes
     registering the same pattern do not error in Python: the second shadows
     the first silently, and the shadowed metric disappears from the report
     without ever having failed.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

AQUI = Path(__file__).resolve().parent

_FUTURE = re.compile(r"^from __future__ import .*$", re.M)
_IMPORT = re.compile(r"^(?:import |from (?!__future__)\S+ import ).*$", re.M)
_PADRAO = re.compile(r'^@sonda\(\s*\n?\s*"([^"]+)"', re.M)


class Colisao(ValueError):
    """Two operations register the same metric pattern. A refusal, never a warning."""


def _corpo(texto: str) -> str:
    """The file without the import lines — they go to the top of the result."""
    sem_future = _FUTURE.sub("", texto)
    return _IMPORT.sub("", sem_future)


def _imports(texto: str) -> list[str]:
    return [linha.strip() for linha in _IMPORT.findall(texto)]


def padroes(texto: str) -> list[str]:
    """The metric patterns this file registers."""
    return _PADRAO.findall(texto)


def juntar(nomes: list[str], raiz: Path = AQUI) -> str:
    fontes: dict[str, str] = {}
    for nome in nomes:
        arquivo = raiz / nome / "sondas.py"
        if not arquivo.is_file():
            # ⚠️ An operation that does not exist is a REFUSAL, and never one
            # file less written silently: `foja` for `forja` would produce half
            # the requested probes, with no error, and nobody would count the
            # ones that were missing.
            disponiveis = sorted(p.name for p in raiz.iterdir() if (p / "sondas.py").is_file())
            raise FileNotFoundError(
                f"`{nome}` is not an operation with probes. There are: {', '.join(disponiveis)}"
            )
        fontes[nome] = arquivo.read_text(encoding="utf-8")

    dono: dict[str, str] = {}
    for nome, texto in fontes.items():
        for padrao in padroes(texto):
            if padrao in dono:
                raise Colisao(
                    f"`{padrao}` is registered by `{dono[padrao]}` and by `{nome}`. "
                    "In Python the second shadows the first with no error at all, and the shadowed "
                    "metric disappears from the report without ever having failed. Rename one of "
                    "the two before joining."
                )
            dono[padrao] = nome

    cabeca = [
        '"""Probes from: ' + ", ".join(nomes) + ".",
        "",
        "Generated by `operacoes/juntar.py`. Editing here is legitimate — this file is yours,",
        "and from here on it does not go back to the tool that wrote it.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    vistos: set[str] = set()
    for texto in fontes.values():
        for linha in _imports(texto):
            if linha not in vistos:
                vistos.add(linha)
                cabeca.append(linha)

    partes = ["\n".join(cabeca), ""]
    for nome, texto in fontes.items():
        partes.append(f"\n# {'=' * 68}\n# {nome}\n# {'=' * 68}\n")
        partes.append(_corpo(texto).strip("\n"))
    return "\n".join(partes) + "\n"


def _console_em_utf8() -> None:
    """The Windows console opens in cp1252 and blows up on `✓` and `⛔`.

    Fails open: if the stream will not take it, we carry on with what we get. A
    refusal that dies over a symbol is not a refusal — it is a traceback.
    """
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[union-attr]
        except (AttributeError, ValueError, OSError):
            pass


def main(argv: list[str] | None = None) -> int:
    _console_em_utf8()
    argv = list(sys.argv[1:] if argv is None else argv)
    saida = None
    if "--saida" in argv:
        i = argv.index("--saida")
        saida = Path(argv[i + 1])
        del argv[i : i + 2]
    nomes = [a for a in argv if not a.startswith("-")]
    if len(nomes) < 2:
        print(__doc__)
        return 2
    try:
        texto = juntar(nomes)
    except (Colisao, FileNotFoundError) as recusa:
        print(f"⛔ REFUSED  {recusa}")
        print()
        print("   Nothing was written. A half-written `sondas.py` is worse than none:")
        print("   it imports, runs, and returns green over what was left out.")
        return 1

    quantos = len(padroes(texto))
    if saida is None:
        print(texto)
        return 0
    saida.parent.mkdir(parents=True, exist_ok=True)
    saida.write_text(texto, encoding="utf-8")
    print(f"✓ {saida}  ·  {len(nomes)} operations, {quantos} probes, 0 collisions")
    print()
    print("  Check with:  python -m loadline /path/to/your/repo --sondas")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
